# Generated by Django 2.1.1 on 2019-01-31 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190131_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiudadEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('la_ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormadetrabajoEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('como_trabaja', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadesEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=50)),
                ('experiencia', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='coderentity',
            name='ciudad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CiudadEntity'),
        ),
    ]
