# Generated by Django 2.1.1 on 2019-02-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190131_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderentity',
            name='cedula',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coderentity',
            name='experiencia',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='habilidadesentity',
            name='experiencia',
            field=models.IntegerField(),
        ),
    ]
