# Generated by Django 2.1.1 on 2019-02-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190201_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderentity',
            name='forma_trabajo',
            field=models.ManyToManyField(to='api.FormadetrabajoEntity'),
        ),
    ]
